# Config file for https://travis-ci.org/

language: php

services:
  - docker

before_install:
  - docker build -t trip-cost-calculator .

# Define the php versions against we want to test our code
php:
  - 7.4

# Note: Code coverage requires php-xDebug extension enabled on CI server

install:
  - docker exec -it trip-cost-calculator travis_retry composer install --no-interaction --no-suggest

# Testing the app (see phpunit.xml) for configs, generating Code Coverage report
script:
  - docker exec -it trip-cost-calculator composer test -- --coverage-clover=coverage.xml

#after_script:

after_success:
  # Submit coverage report to https://codecov.io
  - docker exec -it trip-cost-calculator bash <(curl -s https://codecov.io/bash)

#after_failure:

# Monitor only these branches
branches:
  only:
    - main
    - dev

# You can delete the cache using travis-ci web interface
cache:
  directories:
    - $HOME/.composer/cache